openapi: 3.0.0
info:
  title: FinAI Backend API
  version: 1.0.0
description: API documentation for the FinAI personal finance assistant backend services.

servers:
  - url: http://localhost:8000/api/v1
    description: Local Development Server
  - url: https://api.finai.com/v1
    description: Production Server

tags:
  - name: Auth
    description: User authentication and registration
  - name: Users
    description: User profile management
  - name: Transactions
    description: Financial transaction management
  - name: Budgets
    description: Budget creation and tracking
  - name: Savings
    description: Savings goal management
  - name: Investments
    description: Investment insights and linking
  - name: Goals
    description: Overall financial goal management

paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
      responses:
        '201':
          description: User successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
  # ... (More paths will be automatically generated by FastAPI based on code)

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    UserCreate:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
    UserResponse:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
    # ... (More schemas will be automatically generated by FastAPI Pydantic models)
