name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python environment (Backend & ML Service)
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Setup Node.js environment (Frontend)
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Backend dependencies
      run: | 
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
      working-directory: backend

    - name: Run Backend tests
      run: pytest tests/
      working-directory: backend

    - name: Install ML Service dependencies
      run: pip install -r ml_service/requirements.txt
      working-directory: ml_service

    - name: Run ML Service tests
      run: pytest tests/
      working-directory: ml_service

    - name: Install Frontend dependencies
      run: npm install
      working-directory: frontend

    - name: Run Frontend tests
      run: npm test
      working-directory: frontend

    - name: Build Frontend
      run: npm run build
      working-directory: frontend

    # Further steps for Docker image build and deployment to AWS Fargate
    # (e.g., configure AWS credentials, login to ECR, build & push images)
    # These would typically involve secrets and more complex AWS CLI commands.
